### ISSUE TITLE
Cargando programación... (0%)

### ISSUE THREAD

**Issue by LittleTale** [darkxex/RipJKNX#14]
Cuando prendo la app via el menú Switch después de instalar el NSP y poner el .nro en la carpeta Switch, se queda en cargando programación a 0% y nunca carga. Tengo internet funcional en el Switch (puedo bajar aplicación de tinfoil y usar app de Youtube)

Estoy en en OFW 10.2.0

**Comment by Kronos2308** [comment]
el shtealt mode de sxos posiblemente 
si usas el ultimo commit no deberia pasar
