### ISSUE TITLE
Soporte para ver videos Online para SX OS

### ISSUE THREAD

**Issue by francovp** [darkxex/RipJKNX#2]
Sería genial tener la posibilidad de ver videos de forma online también para usuarios de SX OS. 
No sé las limitantes técnicas o por qué no lo soportas oficialmente, para eso es este Issue.

Buen trabajo de todas formas ☺️

**Comment by darkxex** [comment]
porq sx os no puede. no es parte de la app.

**Comment by francovp** [comment]
¿Dónde está documentada esa supuesta limitante para investigar más? No debería haber cerrado el Issue :/
