### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by AquaHox** [darkxex/RipJKNX#3]
Is that possible to do the same but with other language like french ?

**Comment by darkxex** [comment]
I'm sorry my friend, but this application was designed especially for Spanish speaking audiences. to support another language, something new would have to be done.

**Comment by kbetsu** [comment]
> Is that possible to do the same but with other language like french ?

no woey

**Comment by kbetsu** [comment]
> I'm sorry my friend, but this application was designed especially for Spanish speaking audiences. to support another language, something new would have to be done.

le pueden agregar alguna funcion para poder abrir el navegador? browsenx no mefunciona

**Comment by darkxex** [comment]
Si puedo amigo, te parece q en la siguiente update al presionar L te permita ingresar a alguna página web escrita.

**Comment by kbetsu** [comment]
> Si puedo amigo, te parece q en la siguiente update al presionar L te permita ingresar a alguna página web escrita.

musha gracia amigou ♥
