### ISSUE TITLE
Animeflv API

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [darkxex/RipJKNX#4]
_Saludos @darkxex ,_ 

_Estuve viendo su proyecto, y me llamo tremendamente la atención de que lo hayas llevado a la NX.
Tengo un api que desarrolle de [animeflv](https://github.com/ChrisMichaelPerezSantiago/animeflv) que tal vez le pueda ser de utilidad para extraer datos sobre anime, servers, etc._

_De estar interesado en utilizarlo puedes contactarme para más detalles._

**Comment by darkxex** [comment]
Se ve genial amigo pero desgraciadamente la mayoría del contenido esta basado en jkanime por ende no podría darle utilidad a esa api por ahora.

**Comment by ChrisMichaelPerezSantiago** [comment]
Claro, no problema. A la orden!
