### ISSUE TITLE
Videos se cierran despues de 5 minutos.

### ISSUE THREAD

**Issue by kite21** [darkxex/RipJKNX#52]
Hola, este problema lo empecé a tener después de actualizar mi consola. Yo estaba en la version 10,0 y actualice a la mas reciente (12.1). Después de eso cada que veo un capitulo de cualquier anime, ya sea en JKAnime o anime FLV, me sale este mensaje después de pasados 5 minutos: 

![Web_Browser_7_16_2021_6_38_45_PM](https://user-images.githubusercontent.com/45868869/126018111-e6058575-585e-4473-93f1-f395d56cecb9.jpg)

Después de eso me regresa al menu principal de la app. Si vuelvo a poner el capitulo y lo adelanto vuelve a pasar lo mismo pasados otros 5 minutos. No importa que server use, en todos pasa lo mismo. Agradezco su ayuda.

**Comment by Thyrnt** [comment]
Yo estoy teniendo el mismo problema, si alguien por favor sepa cómo solucionarlo.

**Comment by darkxex** [comment]
Intenta preguntar en el fork de Kronos2308, el actualmente sigue actualizando este proyecto.

**Comment by Thyrnt** [comment]
@kite21 si puedes contribuye con todo lo que puedas y dar detalles de las versiones que tienes de atmosphere, etc, en este post:

https://github.com/StarDustCFW/StarDustCFWPack/issues/14#issue-952585864

Para que el desarrollador pueda encontrar el problema y solucionarlo.

**Comment by Kronos2308** [comment]
![r](https://lewd.pics/p/UQXq.jpg)

**Comment by Thyrnt** [comment]
Como ya está solucionado creo que pueden cerrar este tema.

**Comment by darkxex** [comment]
Chicos, se ha actualizado a la 2.0, ahora la nueva implementación de fembed permite descargar y ver online de este servidor, también se corrigió la descripción de series. 
como ya se dieron cuenta, el problema tiene que ver con los DNS. **así que solo usen incognito** como método de protección antiban.

**Comment by kite21** [comment]
Muchas gracias! Agradezco la atención.
