### ISSUE TITLE
Se cierra al abrir nsp

### ISSUE THREAD

**Issue by davidabsenta** [darkxex/RipJKNX#68]
Estoy en 12.1 con ams 0.19.5 y al abrir la app se crashea la consola .
Error Code: 2345-0008 (0x1159) Program: 05B9DB505ABBE000

Firmware: 12.1.0 (Atmosphère M 0.19.5-master-9df13781c)

An error has occurred.

Please press the POWER Button to restart the console normally, or a VOL button to reboot to a payload (or RCM, if none is present). If you are unable to restart the console, hold the POWER Button for 12 seconds to turn the console off.

If the problem persists, refer to the Nintendo Support Website.

**Comment by darkxex** [comment]
prueba con  la nueva actualización.

**Comment by Kronos2308** [comment]
@davidabsenta  si ese error es el que se arregló en la 2.1.1 era porque no encontraba favoritos y se colgaba y se llevaba la consola
