### ISSUE TITLE
Hola master, podrías implementar un menu de opciónes para personalizar algunas cosas

### ISSUE THREAD

**Issue by diegosauriorexg** [darkxex/RipJKNX#7]
Hola, sugiero que si puedes implementar un menú de opciones para personalizar el background y quitar la música ya que así hace que el usuario se sienta más cómodo. Me parece una de las mejores cosas que me he encontrado en la scene y que mejor que sea de CL.

**Comment by darkxex** [comment]
hola amigo.... no actualizo muy seguido esta app, solo recordar que con start puedes pausar la música. saludos.
