### ISSUE TITLE
A system update is required

### ISSUE THREAD

**Issue by LittleTale** [darkxex/RipJKNX#73]
Hola, cada vez que quiero ver un anime, lanzo un servidor como fembed 2 por ejemplo y el switch me dice "A system update is required before you can proceed"

no entiendo porque, estoy en emuMMC 12.0.3/AMS M.19.5/E
tengo 90DNS en mi wifi y tengo los host block de atmosphere activados !

**Comment by darkxex** [comment]
Actualiza a 12.1 y quita 90dns, la app no funciona con dns modificados en la última versión.
