### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by carnby77** [darkxex/RipJKNX#79]
it still say version 2.2.1 on the homebrew menu

**Comment by darkxex** [comment]
1. por qué escribes en ingles si la app es en español?
2.  ese número los pongo al azar. así que no te sorprendas si ese número se actualiza o no, solo fíjate que hayas descargado el latest build.

**Comment by carnby77** [comment]
no seas tonto. ¡No todas las personas hablan tu patético idioma! estás creando contenido para un dispositivo que es mundial ... aprende inglés, idiota

**Comment by darkxex** [comment]
creo que estás cometiendo un error, esta aplicación se creo solo para gente que habla el "patético idioma español", si crees que miento intenta buscar cualquier serie o capítulo y verás que está subtitulado en español. saludos y si deseas usar esta app te recomiendo saber español.

**Comment by Kronos2308** [comment]
ese es comepinga y anormal al rente el culo
