### ISSUE TITLE
Puedo ayudar con el proyecto?

### ISSUE THREAD

**Issue by Kronos2308** [darkxex/RipJKNX#8]
Veo que este proyecto tiene  potencial 
pero se puede mejorar algo la interfaz y el codigo
![e](https://lewd.pics/p/qanA.jpg)

![e](https://lewd.pics/p/bOyQ.jpg)

algo asi pra empezar luego se puede pulir mas

**Comment by darkxex** [comment]
Claro, eres libre de editarlo a tu gusto, es código abierto.

**Comment by Kronos2308** [comment]
hay te deje un Pull request para que piedas revisar el cadigo y me des tu impresion @darkxex

**Comment by darkxex** [comment]
Ya lo aprobé, desgraciadamente no cuento con el tiempo de darle una mirada pero eres libre de modificar lo que quieras.
